# Generated by Django 5.2.4 on 2025-08-01 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '初级'), (2, '中级'), (3, '高级'), (4, '专家')], unique=True, verbose_name='难度等级')),
                ('name', models.CharField(max_length=20, verbose_name='难度名称')),
            ],
            options={
                'verbose_name': '难度',
                'verbose_name_plural': '难度',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='题目标题')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('answer', models.TextField(verbose_name='参考答案')),
                ('key_points', models.TextField(blank=True, verbose_name='关键要点')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='标签')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baguwen.category', verbose_name='分类')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baguwen.difficulty', verbose_name='难度')),
            ],
            options={
                'verbose_name': '八股文题目',
                'verbose_name_plural': '八股文题目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baguwen.question', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
