# Generated by Django 5.2.4 on 2025-08-01 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baguwen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('excel', 'Excel文件'), ('json', 'JSON文件'), ('manual', '手动批量'), ('api', 'API导入')], max_length=20, verbose_name='导入类型')),
                ('file_name', models.CharField(blank=True, max_length=200, verbose_name='文件名')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='总数量')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='成功数量')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='失败数量')),
                ('error_log', models.TextField(blank=True, verbose_name='错误日志')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='导入人')),
            ],
            options={
                'verbose_name': '导入记录',
                'verbose_name_plural': '导入记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
